# todo


services:
  ordersystem-db:
    image: postgres:18
    container_name: ordersystem-db
    environment:
      POSTGRES_DB: order
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgdata_sbd:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - sbdnetwork

  orderservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orderservice
    environment:
      POSTGRES_DB: order
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_TCP_PORT: 5432
      DB_HOST: ordersystem-db
    ports:
      - "3000:3000"
    depends_on:
      - ordersystem-db
    networks:
      - sbdnetwork

volumes:
  pgdata_sbd:

networks:
  sbdnetwork:
